    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">Luigi's Pizza
                <img id="logo-navbar" src="logo-navbar.png">
              </a>
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="LuigisPizzaBestellen.html" id="Bestellen-Navbar">Bestellen</a></li>
                <li><a href="#">Kontakt</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
