

    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <link rel="stylesheet" href="LuigisPizzaTemplate.css" type="text/css">
    <link rel="stylesheet" href="LuigisPizzaContent.css" type="text/css">
    <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../node_modules/tablesorter/dist/css/theme.bootstrap.min.css">

    <script src="../node_modules/jquery/dist/jquery.js"></script>
    <script src="../node_modules/jquery/dist/jquery.min.js"></script>
    <script src="../node_modules/tablesorter/dist/js/jquery.tablesorter.js"></script>
    <script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      $(function() {
        $("#mytable").tablesorter();
      });
    </script>

    <title>Luigi's Pizza</title>
    <link rel="icon" href="logo-icon.ico"/>

    <?php
      $Header="LuigisPizzaHeader.inc";
      $Footer="LuigisPizzaFooter.inc";
    ?>
